web:
  build: .
  ports:
    - "6023:6023"
  links:
    - mongo
  working_dir: /app
  volumes: 
    - .:/app
  command: python sc_spider/execute.py crawl songsan -o out/items.jl
mongo:
  image: mongo
  volumes:
    - data:/data
  ports:
    - "27017:27017"
